name: skinsight
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  another_flushbar: ^1.12.30
  bloc: ^9.0.0
  camera: ^0.11.2
  camerawesome: ^2.5.0
  connectivity_plus: ^6.1.4
  crop_your_image: ^1.0.6
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dash_chat_2: ^0.0.21
  dio: ^5.8.0+1
  equatable: ^2.0.5
  extended_image: ^8.1.1
  extended_markdown_viewer: ^0.3.0
  face_camera: ^0.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_image_compress: ^2.1.0
  flutter_markdown: ^0.7.7+1
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.2.0
  font_awesome_flutter: ^10.8.0
  geolocator: ^10.1.0
  get_it: ^8.0.3
  google_fonts: ^6.1.0
  http: ^1.4.0
  http_parser: ^4.1.2
  iconsax: ^0.0.8
  image_cropper: ^9.1.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  lottie: ^3.3.1
  open_file: ^3.5.10
  path_provider: ^2.1.5
  pinput: ^5.0.1
  pretty_dio_logger: ^1.4.0
  quickalert: ^1.1.0
  readmore: ^3.0.0
  share_plus: ^11.0.0
  shared_preferences: ^2.2.1
  shimmer: ^3.0.0
  skeletonizer: ^1.4.3
  sliver_tools: ^0.2.12
  url_launcher: ^6.3.2

dependency_overrides:
  camera_android: ^0.10.5+6

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/sizuka.gif
    - assets/scan.gif
    - assets/scan_text.gif

